### ISSUE TITLE
Linux build - files needed

### ISSUE THREAD

**Issue by crshrprt** [ardura/Scrollscope#8] opened 2024-01-28 10:27 UTC
I was trying to build this plugin on Linux and I encountered an error:
```
$ cargo xtask bundle scrollscope --release
error: no such command: `xtask`

	Did you mean `test`?

	View all installed commands with `cargo --list`
	Find a package to install `xtask` with `cargo search cargo-xtask`
```
After a brief look of the latest  commits I have seen there are several files removed from the main branch.
Going back to the v.1.1 tag and manually cloning nih-plug I managed to start building it but I encountered another error:
```
error[E0053]: method `editor` has an incompatible type for trait
   --> src/lib.rs:141:15
    |
141 |     fn editor(&self, _async_executor: AsyncExecutor<Self>) -> Option<Box<dyn Editor>> {
    |               ^^^^^
    |               |
    |               types differ in mutability
    |               help: change the self-receiver type to match the trait: `&mut self`
    |
    = note: expected signature `fn(&mut Gain, nih_plug::prelude::AsyncExecutor<_>) -> Option<_>`
               found signature `fn(&Gain, nih_plug::prelude::AsyncExecutor<_>) -> Option<_>`

For more information about this error, try `rustc --explain E0053`.
error: could not compile `scrollscope` (lib) due to 1 previous error
Error: Could not build scrollscope

```

**Comment by ardura** [comment] 2024-01-28 18:20
I remember that is caused by nih-plug versions so I need to update the cargo and the version referenced since I remember one of the versions of nih-plug changes the self reference for plugins. I'll take a look at this tomorrow

**Comment by ardura** [comment] 2024-01-29 15:13
Hi crshrpt, This should be fixed in this commit. Sorry about that! https://github.com/ardura/Scrollscope/commit/0f0c1fcbc66dd75b4e967dc2a2d2092ceea1044e :)

**Closed by ardura** 2024-01-29 15:13 UTC

**Comment by crshrprt** [comment] 2024-01-29 16:41
Thank you! I can confirm it works now, awesome plugin! :)
